baseurl                  = "https://pestrickland.co.uk/" # Your domain name. Must end with "/"
languageCode             = "en-gb"
defaultContentLanguage   = "en"
title                    = "Paul Strickland"
enableEmoji              = true

[author]
name                     = "Paul Strickland"
headline                 = "An aerospace engineer who likes to run, sew, knit and spin"
image                    = "profile.jpg"

links = [
    { github = "https://www.github.com/pestrickland" },
    { email = "mailto:paul@pestrickland.co.uk" },
    { gitlab = "https://gitlab.com/pestrickland" },
    { instagram = "https://instagram.com/pestrickland" },
    { keybase = "https://keybase.io/pestrickland" },
    { linkedin = "https://linkedin.com/in/pestrickland" },
    { mastodon = "https://mastodon.social/@pestrickland" },
    { reddit = "https://reddit.com/user/pestrickland" },
    { strava = { href = "https://www.strava.com/athletes/paul_strickland", text = "Strava" }},
    { substack = { href = "https://pestrickland.substack.com/", text = "Substack"}},
]

[module]
    [module.hugoVersion]
        extended = false
        min = "0.86.1"


# Metadata
#    description          = "The homepage of Paul Strickland, an aerospace engineer working in the UK defence industry" # Max 160 characters show in search results
